$env:SPECIALIST_BOOKING_API_PORT = "8080"
$env:SPECIALIST_BOOKING_API_MONGODB_HOST = "localhost"
$env:SPECIALIST_BOOKING_API_MONGODB_PORT = "27017"
$env:SPECIALIST_BOOKING_API_MONGODB_USERNAME = "root"
$env:SPECIALIST_BOOKING_API_MONGODB_PASSWORD = "example"

go run ./cmd/specialist-booking-api-service
